batch_size: 4
gradient_accumulation_steps: 1
lr: 3.0e-4
warm_up: 0.01
warm_up_iters: 200
lora_r: 16
lora_alpha: 32
epochs: 30000000
save_interval: 300
log_interval: 10
bmt_cpu_offload: False
bmt_pre_load: True

save_optim: True
save_rng: True

eps: 1.0e-8
lora: True

enable_sft_dataset_dir: './data/'
enable_sft_dataset_file: 'convo_samples.jsonl'
