batch_size: 4
gradient_accumulation_steps: 1
lr: 3.0e-4
warm_up: 0.01

bmt_cpu_offload: False
bmt_pre_load: True
save_interval: 300
log_interval: 10
warm_up_iters: 100
save_optim: True
save_rng: True
lora: False
eps: 1.0e-8
enable_sft_dataset_dir: './data/'
enable_sft_dataset_file: 'sft_v0.9.4_train.jsonl'
