name: Build

on:
  pull_request_target:
    types: [opened, reopened, synchronize]
    branches:
      - 'dev'
      - 'main'
  push:
    branches:
      - 'dev'

jobs:
  build-archive-wheel:
    
    uses: OpenBMB/BMTrain/.github/workflows/build_whl.yml@main
    secrets: inherit

  fake-publish:
    needs: build-archive-wheel
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set Up the Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Download distribution files
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist
