batch_size: 10
gradient_accumulation_steps: 1
lr: 2.0e-5
warm_up: 0.01
save_interval: 1000

bmt_cpu_offload: False
bmt_pre_load: False
bmt_async_load: False
bmt_loss_scale: 524288

save_optim: True
save_rng: True

load_optim: False
resume_dataset: False