name: 'onnx docker'

on:
  workflow_dispatch:
  push:
    branches: ['master']
    paths:
      - 'onnx/Dockerfile'
      - 'onnx/export/**'
      - 'onnx/misc/**'
      - 'onnx/version.txt'
      - '.github/workflow/onnx.yml'
  pull_request:
    branches: ['master']
    paths:
      - 'onnx/Dockerfile'
      - 'onnx/export/**'
      - 'onnx/misc/**'
      - 'onnx/version.txt'
      - '.github/workflow/onnx.yml'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set Env
        run: |
          VERSION=$(cat onnx/version.txt)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./onnx/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{secrets.DOCKER_ORG}}/altclip-onnx:latest, ${{secrets.DOCKER_ORG}}/altclip-onnx:${{env.VERSION}}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            GIT=https://github.com/${{github.repository}}.git
